server:
  port: 58087

spring:
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: smtp.yeah.net
    port: 25
    username: lucky_tour@yeah.net
    password: ENC(c6dFJcZQmnZl1m1VFNvi3DfF2qcNBzBdcwtEr2qZwesXEryHZAPUafom402/om7pUg4zaWxF2NSZHWh+sndioQ==)
    test-connection: false
    properties:
      mail:
        smtp:
          auth: false
        debug: false
        mime:
          splitlongparameters: false
  threads:
    virtual:
      enabled: true

logging:
  config: classpath:logback-spring.xml
  aop:
    max-length: 1000

#springdoc相关配置
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'luckytour'
      paths-to-match: '/**'
      packages-to-scan: com.luckytour.server  #改成你自己的包名，一般到启动类的包名
  packages-to-scan:
    - com.luckytour.server.controller
    - com.luckytour.server.entity
    - com.luckytour.server.vo
    - com.luckytour.server.payload
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    # 开启动态请求参数，true-开启，false-关闭
    enable-dynamic-parameter: true

jpush:
  app-key: ENC(Ys1XyqrhmGTCsrtrsNCwo0Z5eC5oknrhSqMjHYNkC/roWnhIAp/Lvzi+xkCs8V2I/nZw3qumv7iO0TNBq+i38w==)
  master-secret: ENC(zv1qC94mu453kP8fsc3o3qHa61wt7K07SygaFdeTiiyYIhfDH/tUYcTvU1oCIqEZ7ONhb84LLdnZrI9JbtTdAg==)
  live-time: 1000
  apns-production: false

mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_empty

jwt:
  # 至少44位长，采用圆周率小数点后44位
  secret-key: ENC(kOUiYgry3xli9QL3PZBVtc9MufPfDRjeP88MOcriP7lXwRbV7cBSjbyjUlhUzK5X5g9h6mRkeE8rRrPDjWDKtWa5dSU+RPT0cy1mtFUZX/o=)
  short-ttl: 600000
  long-ttl: 604800000

storage:
  folder:
    default-format: yyyy/MM/dd
  static:
    path: static
    avatar:
      path: avatar
      default: https://cdn.jsdelivr.net/gh/Jin1c-3/picx-images-hosting@master/20240110/luckytour-logo-round.1w2sagoaz074.webp
    blog:
      path: blog
      pic:
        path: pic

api:
  gaode:
    key: ENC(yMFeHgGQGfRIcNMZHoaKZW/4mUiIK8+52+ScrMOvqYGKMt6g7Y6Lmo7ph4/XWKAerCOG6SNqi91vHcM3pvCdOeZaIhnNk4sX6LFBWve9aP0=)
    distance: https://restapi.amap.com/v3/distance
    geocode: https://restapi.amap.com/v3/geocode/geo
  caiyun:
    key: ENC(rA9BtN+2c2RQpC+o8nhHFUZCWN6KqpcPwjzGK0MxiiqyX5tDpDjIcxMvf3WZBBcpDOwJf9IOknYdBmGPAQRDkA==)
    daily-weather: https://api.caiyunapp.com/v2.6/%s/%s/daily?dailysteps=15
    hourly-weather: https://api.caiyunapp.com/v2.6/%s/%s/hourly?hourlysteps=15
    check-hours: 4
  flask:
    chat: /chat
    plan-generator:
      url: /generatePlanner
      prompt-field: prompt
      counter: 3 # 计划重新生成的次数，-1表示无穷大
      wait-time: 50000 # 重新生成计划的等待时间

code:
  user-id:
    max-length: 6
    min-length: 11
  verification:
    code-length: 5
    expire-time: 300000

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    string-output-type: base64
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

cache:
  ttl: 30 # 缓存时间，单位分钟